-- 80% da lotação em aberto (48 vagas × 80% = 38 veículos)
-- Execute na pasta backend: sqlite3 estacionamento.db < seed-abertos-80pct.sql

INSERT INTO registro_estacionamento (placa, marca, modelo, cor, horario_entrada, horario_saida, valor_cobrado, created_at) VALUES
('OPN1001', 'Volkswagen', 'Gol', 'Prata', datetime('now', '-2 hours'), NULL, NULL, datetime('now')),
('OPN1002', 'Fiat', 'Uno', 'Preto', datetime('now', '-45 minutes'), NULL, NULL, datetime('now')),
('OPN1003', 'Chevrolet', 'Onix', 'Branco', datetime('now', '-1 hour'), NULL, NULL, datetime('now')),
('OPN1004', 'Hyundai', 'HB20', 'Vermelho', datetime('now', '-3 hours'), NULL, NULL, datetime('now')),
('OPN1005', 'Renault', 'Sandero', 'Cinza', datetime('now', '-20 minutes'), NULL, NULL, datetime('now')),
('OPN1006', 'Ford', 'Ka', 'Azul', datetime('now', '-90 minutes'), NULL, NULL, datetime('now')),
('OPN1007', 'Toyota', 'Corolla', 'Prata', datetime('now', '-5 hours'), NULL, NULL, datetime('now')),
('OPN1008', 'Honda', 'Civic', 'Preto', datetime('now', '-15 minutes'), NULL, NULL, datetime('now')),
('OPN1009', 'Jeep', 'Renegade', 'Branco', datetime('now', '-1 hour'), NULL, NULL, datetime('now')),
('OPN1010', 'Nissan', 'Kicks', 'Verde', datetime('now', '-30 minutes'), NULL, NULL, datetime('now')),
('OPN1011', 'Chevrolet', 'Tracker', 'Preto', datetime('now', '-4 hours'), NULL, NULL, datetime('now')),
('OPN1012', 'Volkswagen', 'Polo', 'Cinza', datetime('now', '-50 minutes'), NULL, NULL, datetime('now')),
('OPN1013', 'Fiat', 'Argo', 'Branco', datetime('now', '-2 hours'), NULL, NULL, datetime('now')),
('OPN1014', 'Hyundai', 'Creta', 'Azul', datetime('now', '-6 hours'), NULL, NULL, datetime('now')),
('OPN1015', 'Renault', 'Duster', 'Marrom', datetime('now', '-25 minutes'), NULL, NULL, datetime('now')),
('OPN1016', 'Toyota', 'Hilux', 'Prata', datetime('now', '-3 hours'), NULL, NULL, datetime('now')),
('OPN1017', 'Honda', 'HR-V', 'Vermelho', datetime('now', '-40 minutes'), NULL, NULL, datetime('now')),
('OPN1018', 'Ford', 'EcoSport', 'Verde', datetime('now', '-1 hour'), NULL, NULL, datetime('now')),
('OPN1019', 'Jeep', 'Compass', 'Bege', datetime('now', '-70 minutes'), NULL, NULL, datetime('now')),
('OPN1020', 'BMW', 'X1', 'Preto', datetime('now', '-2 hours'), NULL, NULL, datetime('now')),
('OPN1021', 'Mercedes-Benz', 'Classe C', 'Prata', datetime('now', '-10 minutes'), NULL, NULL, datetime('now')),
('OPN1022', 'Audi', 'A3', 'Branco', datetime('now', '-5 hours'), NULL, NULL, datetime('now')),
('OPN1023', 'Nissan', 'Versa', 'Cinza', datetime('now', '-55 minutes'), NULL, NULL, datetime('now')),
('OPN1024', 'Mitsubishi', 'L200', 'Preto', datetime('now', '-3 hours'), NULL, NULL, datetime('now')),
('OPN1025', 'Peugeot', '208', 'Azul', datetime('now', '-35 minutes'), NULL, NULL, datetime('now')),
('OPN1026', 'Citroen', 'C3', 'Vermelho', datetime('now', '-1 hour'), NULL, NULL, datetime('now')),
('OPN1027', 'Chevrolet', 'Spin', 'Prata', datetime('now', '-2 hours'), NULL, NULL, datetime('now')),
('OPN1028', 'Volkswagen', 'T-Cross', 'Verde', datetime('now', '-45 minutes'), NULL, NULL, datetime('now')),
('OPN1029', 'Fiat', 'Cronos', 'Preto', datetime('now', '-4 hours'), NULL, NULL, datetime('now')),
('OPN1030', 'Hyundai', 'Tucson', 'Branco', datetime('now', '-20 minutes'), NULL, NULL, datetime('now')),
('OPN1031', 'Renault', 'Kwid', 'Amarelo', datetime('now', '-90 minutes'), NULL, NULL, datetime('now')),
('OPN1032', 'Ford', 'Territory', 'Cinza', datetime('now', '-1 hour'), NULL, NULL, datetime('now')),
('OPN1033', 'Toyota', 'Yaris', 'Prata', datetime('now', '-15 minutes'), NULL, NULL, datetime('now')),
('OPN1034', 'Honda', 'Fit', 'Azul', datetime('now', '-3 hours'), NULL, NULL, datetime('now')),
('OPN1035', 'Jeep', 'Renegade', 'Marrom', datetime('now', '-50 minutes'), NULL, NULL, datetime('now')),
('OPN1036', 'Chevrolet', 'Prisma', 'Preto', datetime('now', '-2 hours'), NULL, NULL, datetime('now')),
('OPN1037', 'Volkswagen', 'Nivus', 'Vermelho', datetime('now', '-30 minutes'), NULL, NULL, datetime('now')),
('OPN1038', 'Fiat', 'Mobi', 'Branco', datetime('now', '-6 hours'), NULL, NULL, datetime('now'));
